package com.tnl.logistics.model;

/**
 * 4-state lifecycle for Waybill physical custody and proof-of-delivery turnover:
 * GENERATED: Waybill document generated by office staff with parcel snapshot and designated hauler.
 * SENT_TO_HAULER: Freight and physical paper manifest dispatched with 3rd-party hauler.
 * SIGNED_COMPLETED: Client signed physical POD, driver returned paper to admin, and delivery is finalized.
 */
public enum WaybillStatus {
    GENERATED,
    SENT_TO_HAULER,
    SIGNED_COMPLETED
}
