spring.application.name=logistics
spring.profiles.active=dev

spring.jackson.serialization.write-dates-as-timestamps=false

logging.level.root=INFO
logging.level.com.tnl.logistics=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
