spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate # Strictly validate schema integrity in production
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  flyway:
    enabled: true
    baseline-on-migrate: false
